snd-soc-apple-mca-objs	    := mca.o
snd-soc-apple-silicon-objs	:= macaudio.o

obj-$(CONFIG_SND_SOC_APPLE_MCA)     += snd-soc-apple-mca.o
obj-$(CONFIG_SND_SOC_APPLE_SILICON) += snd-soc-apple-silicon.o

